# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: 'Github token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'