#
# Dockerfile used to generate https://hub.docker.com/repository/docker/taotesting/tao-release
#
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV TZ=Europe/Luxembourg

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-add-repository ppa:ondrej/php
RUN apt-get update
RUN apt-get install -y php8.3 php8.3-pdo php8.3-mbstring php8.3-dom php8.3-zip php8.3-gd php8.3-curl npm git jq python3 g++ make curl
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get install -y nodejs
RUN npm i -g @oat-sa/tao-extension-release
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN composer self-update

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

CMD ["/bin/bash"]
